version: "3.9"
services:

  mysql9:
    image: mysql:9
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres16:
    image: postgres:16-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    image: usuarios:latest
    ports:
      - "8001:8001"
    environment:
      PORT: "8001"
    networks:
      - spring
    depends_on:
      - mysql9
    restart: always


  msvc-cursos:
    image: cursos:latest
    ports:
      - "8002:8002"
    environment:
      PORT: "8002"
    networks:
      - spring
    depends_on:
      - postgres16
    restart: always

volumes:
  data-mysql:
  data-postgres:


networks:
  spring:
    driver: bridge
